### ISSUE TITLE
conventions pour les noms

### ISSUE THREAD

**Issue by physcrowley** [101010101010101011010/ObjetSimple#1]
@101010101010101011010  Le projet est bien structuré et cohérent, repéresentant tout ce qu'on a vu jusqu'à présent. Bravo également pour l'utilisation efficace des `enum`.

Une correction mineure :

- [x] Renommer les méthodes avec une lettre initiale minuscule (seulement les classes et la méthode constructeur [qui reprend le nom de la classe] sont nommées avec une lettre initiale majuscule).

**Comment by 101010101010101011010** [comment]
J'ai modifié les noms des méthodes comme vous avez suggérés.
